### PR TITLE
Skallesh

### PR DESCRIPTION
**Pull request by skallesh**
I have fixed failing bugzilla tests and autoAttachDisabledByOwner tests. 
line no 169 of AutoAttachDisableByOwnerTests.java , exit code has changed from 0 to 1. I feel its a bug as I have little knowledge of exitcodes want to confirm from you if I need to log a bug for it or change the code

### CODE REVIEW

**Comment by jsefler** [comment]
For all of the candlepin message string changes from single quotes to double quotes, I suggest something like this (because it will work with old and new candlepin)....

	expected = String.format("Ignoring request to auto-attach. It is disabled for org '%s'.",owner);
	if (SubscriptionManagerTasks.isVersion(servertasks.statusVersion, ">=", "2.3.1-1")) {	// commit 0d5fefcfa8c1c2485921d2dee6633879b1e06931 Correct incorrect punctuation in user messages
		expected = String.format("Ignoring request to auto-attach. It is disabled for org \"%s\".",owner);
	}

**Comment by jsefler** [comment]
Regarding the register exit code of 1 (instead of 0), this is expected if the system is already registered and gets a stdout result of "This system is already registered. Use --force to override".  Otherwise a successful register should give an exit code of 0.  I am not aware of any recent subscription-manager changes that would affect this.

**Comment by jsefler** [comment]
On line 190 of AutoAttachDisabledByOwnerTests.java, I suggest you code something like this...
// TODO
Assert.fail("Now that bug 1489894 has been fixed, an additional step is needed to accurately assert the registerResult.");

The reason I like this is because it will force a failure and remind us (as automation developers) what needs to be done next.  Without it, the test case will start running as soon as the blockedByBug-1489894 is resolved and the test case may start passing and we will forget to go back and add an extra assert.

**Comment by skallesh** [comment]
Done..thanks , learnt something new today. I like it a lot..

**Pull request merged**
